apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.64.100-192.168.64.110
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ltwo
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
  interfaces:
  - enp0s1