alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'nginx-ingress'
        static_configs:
          - targets: ['ingress-nginx-controller-metrics.ingress-nginx.svc:10254']
