name: Build Canary App Image

on:
  push:
    paths:
      - 'sample-app/v1-works/**'
      - 'sample-app/v2-chaos/**'
      - 'sample-app/v3-works/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - v1-works
          - v2-chaos
          - v3-works

    if: contains(github.event.head_commit.message, matrix.folder) || 
        contains(join(github.event.commits.*.modified, ','), format('sample-app/{0}/', matrix.folder)) ||
        contains(join(github.event.commits.*.added, ','), format('sample-app/{0}/', matrix.folder)) ||
        contains(join(github.event.commits.*.removed, ','), format('sample-app/{0}/', matrix.folder))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./sample-app/${{ matrix.folder }}
          push: true
          tags: aditirvan/canary-app:${{ matrix.folder }}
