name: Build Canary App Image

on:
  push:
    paths:
      - 'sample-app/v1-works/**'
      - 'sample-app/v2-chaos/**'
      - 'sample-app/v3-works/**'

jobs:
  build-v1:
    if: contains(github.event.head_commit.message, 'v1-works') || 
        github.event.head_commit.message == '' # fallback
    runs-on: ubuntu-latest
    name: Build v1-works image
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ./sample-app/v1-works
          push: true
          tags: aditirvan/canary-app:v1-works
          platforms: linux/amd64,linux/arm64

  build-v2:
    if: contains(github.event.head_commit.message, 'v2-chaos') || 
        github.event.head_commit.message == ''
    runs-on: ubuntu-latest
    name: Build v2-chaos image
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ./sample-app/v2-chaos
          push: true
          tags: aditirvan/canary-app:v2-chaos
          platforms: linux/amd64,linux/arm64

  build-v3:
    if: contains(github.event.head_commit.message, 'v3-works') || 
        github.event.head_commit.message == ''
    runs-on: ubuntu-latest
    name: Build v3-works image
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ./sample-app/v3-works
          push: true
          tags: aditirvan/canary-app:v3-works
